/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.rendti.forms;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.security.KeyStore;
import org.apache.pdfbox.examples.signature.CreateSignature;

/**
 *
 * @author rafael
 */
public class FormTeste extends javax.swing.JPanel {

    /**
     * Creates new form FormTeste
     */
    public FormTeste() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("Tente Assinar PDF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("Resultado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            
            /*
        java.security.KeyStore ks  = KeyStore.getInstance(   "JKS");
        String filePathToStore = "C:\\Users\\rafael\\rend_key.keystore";
        String keystorePasswordCharArray = "whatever00";
        String passwordForKeyCharArray = "whatever00";
        
        InputStream readStream = new FileInputStream(filePathToStore);
        ks.load(readStream, keystorePasswordCharArray.toCharArray());
        //Key key = ks.getKey("rafaelrend", passwordForKeyCharArray.toCharArray() );
        CreateSignature obj = new CreateSignature(ks, "whatever00".toCharArray());
        //java.io.File inFile = new java.io.File("C:\\Users\\rafael\\contrato.pdf");
        java.io.File inFile = new File("C:\\Users\\rafael\\contrato.pdf");
        java.io.File inFile2 = new File("C:\\Users\\rafael\\contrato_signed.pdf");
        //InputStream inFile = new FileInputStream("C:\\Users\\rafael\\contrato.pdf");
        //obj.sign(inFile);
        obj.signDetached(inFile, inFile2);

*/
            
        java.security.KeyStore ks  = KeyStore.getInstance("JKS");
        String filePathToStore = "F:\\Unidade G\\Sistemas\\Projetos Web\\Paulao\\Agro\\Interacoes\\certificado\\agro.jks";
        String keystorePasswordCharArray = "123456";
        String passwordForKeyCharArray = "1234";
        String alias = "07d1e09a-dac5-43c9-9a5f-ca30d208ccf0";
        
        
        
        InputStream readStream = new FileInputStream(filePathToStore);
        ks.load(readStream, keystorePasswordCharArray.toCharArray());
        
        ks.getKey(alias, passwordForKeyCharArray.toCharArray() );
        CreateSignature obj = new CreateSignature(ks, passwordForKeyCharArray.toCharArray());
        //java.io.File inFile = new java.io.File("C:\\Users\\rafael\\contrato.pdf");
        java.io.File inFile = new File("F:\\Unidade G\\Sistemas\\Projetos Web\\Paulao\\Agro\\Interacoes\\certificado\\teste.pdf");
        java.io.File inFile2 = new File("F:\\Unidade G\\Sistemas\\Projetos Web\\Paulao\\Agro\\Interacoes\\certificado\\teste_signed.pdf");
        //InputStream inFile = new FileInputStream("C:\\Users\\rafael\\contrato.pdf");
        //obj.sign(inFile);
        obj.signDetached(inFile, inFile2);
        
        }catch(Exception exp){
            Object msg = exp.getMessage();
            System.out.println(exp.getMessage() );
        }
     
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
